# Configuration for homepage setup

# Name of the homepage application
name: Hackn0-homepage

# Service definitions for the homepage application
services:
  # Service name: app
  # The `app` service definition
  app:
    # Image to be used for the container
    image: ghcr.io/gethomepage/homepage:latest

    # Name of the container instance
    container_name: homepage

    # Port mapping between host and container
    ports:
      - 3000:3000 # Maps port 3000 of the host to port 3000 of the container

    # Mount points for volumes (persistent storage)
    volumes:
      # Maps local config directory to the config directory inside the container
      # Ensure the local config directory is created before starting the container
      - /DATA/AppData/$AppID/config:/app/config

      # Maps the Docker socket from the host to the container
      # This allows the container to communicate with the Docker daemon on the host
      - /var/run/docker.sock:/var/run/docker.sock
    x-casaos: # CasaOS specific configuration
      volumes:
        - container: /app/config
          description:
            en_us: "Container Path: /app/config"
        - container: /var/run/docker.sock
          description:
            en_us: "Container Path: /var/run/docker.sock"
      ports:
        - container: "3000"
          description:
            en_us: "Container Port: 3000"

# CasaOS specific configuration
x-casaos:
  # Supported CPU architectures for the application
  architectures:
    - amd64
    - arm64
  # Main service of the application
  main: app
  description:
    # Description in English
    en_us: A modern, fully static, fast, secure fully proxied, highly customizable application dashboard with integrations for over 100 services and translations into multiple languages. Easily configured via YAML files or through docker label discovery.
  tagline:
    # Short description or tagline in English
    en_us: Homepage
  # Developer's name or identifier
  developer: "https://github.com/gethomepage/homepage"
  # Author of this configuration
  author: Hackn0
  # Icon for the application
  icon: https://gethomepage.dev/main/assets/light_squircle@2x.png
  # Thumbnail image (currently empty)
  thumbnail: ""
  title:
    # Title in English
    en_us: Homepage
  # Application category
  category: Hackn0CasaOS
  # Port mapping information
  port_map: "3000"
