name: homepage-hackn0
services:
  app:
    container_name: homepage
    image: ghcr.io/gethomepage/homepage:latest
    ports:
      - target: 3000
        published: ${WEBUI_PORT:-3000}
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/Hackn0/$AppID/app/config
        target: /app/config
      - type: bind
        source: //var/run/docker.sock
        target: /var/run/docker.sock
    restart: unless-stopped

x-casaos:
  architectures:
    - amd64
  author: homepage
  category: Hackn0
  description:
    en_us: A modern, fully static, fast, secure fully proxied, highly customizable application dashboard with integrations for over 100 services and translations into multiple languages. Easily configured via YAML files or through docker label discovery.
  developer: homepage
  icon: https://gethomepage.dev/main/assets/light_squircle@2x.png
  index: /
  main: app
  port_map: ${WEBUI_PORT:-3000}
  scheme: http
  tagline:
    en_us: A modern, fully static, fast, secure fully proxied, highly customizable application dashboard with integrations for over 100 services and translations into multiple languages. Easily configured via YAML files or through docker label discovery.
  store_app_id: homepage-hackn0
  title:
    en_us: Homepage