name: stirling-pdf
services:
  app:
    container_name: stirling-pdf
    image: frooodle/s-pdf:latest
    environment:
      - DOCKER_ENABLE_SECURITY=true
    ports:
      - target: 8080
        published: ${WEBUI_PORT:-8080}
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/Hackn0/$AppID/training-data
        target: /usr/share/tesseract-ocr/4.00/tessdata
      - type: bind
        source: /DATA/AppData/Hackn0/$AppID/configs
        target: /configs
    restart: unless-stopped
    privileged: false

x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  description:
    en_us: This is a powerful locally hosted web based PDF manipulation tool using docker that allows you to perform various operations on PDF files, such as splitting merging, converting, reorganizing, adding images, rotating, compressing, and more.
  developer: stirling-pdf
  icon: https://cdn.jsdelivr.net/gh/mariosemes/CasaOS-TMCstore@main/Apps/stirling-pdf/icon.png
  index: /
  main: app
  port_map: ${WEBUI_PORT:-8080}
  scheme: http
  tagline:
    en_us: This is a powerful locally hosted web based PDF manipulation tool using docker that allows you to perform various operations on PDF files, such as splitting merging, converting, reorganizing, adding images, rotating, compressing, and more.
  tips:
    custom: |-
      Username ```admin``` <br />
      Password ```stirling```
  title:
    en_us: stirling-pdf
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/mariosemes/CasaOS-TMCstore@main/Apps/stirling-pdf/screenshot-01.png
  thumbnail: https://cdn.jsdelivr.net/gh/mariosemes/CasaOS-TMCstore@main/Apps/stirling-pdf/thumbnail.png
  author: Hackn0
  category: Hackn0
  store_app_id: homepage
