name: medusa
services:
  app:
    container_name: medusa
    image: linuxserver/medusa:latest
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: for UserID
        - container: PGID
          description:
            en_us: for GroupID
        - container: TZ
          description:
            en_us: specify a timezone to use, see this list.
    ports:
      - target: 8081
        published: 8081
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/Hackn0/$AppID/config
        target: /config
      - type: bind
        source: /DATA/AppData/Hackn0/$AppID/downloads
        target: /downloads
      - type: bind
        source: /DATA/AppData/Hackn0/$AppID/tv
        target: /tv
x-casaos:
  architectures:
    - amd64
  main: app
  description:
    en_us: 'Visit homepage: https://hub.docker.com/r/linuxserver/medusa/'
  tagline:
    en_us: An automatic Video Library Manager for TV Shows. It watches for new episodes of your favorite shows, and when they are posted it does its magic.
  developer: LinuxServer.io
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/medusa-icon.png
  thumbnail: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/medusa-icon.png
  title:
    en_us: Medusa
  project_url: https://github.com/pymedusa/Medusa
  port_map: '8081'
  author: linuxserver
  category: Hackn0
  store_app_id: medusa

