name: portainer
services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    deploy:
      resources:
        reservations:
          memory: 32M
    network_mode: bridge
    ports:
      - target: 8000
        published: "8000"
        protocol: tcp
      - target: 9000
        published: "9000"
        protocol: tcp
      - target: 9443
        published: "9443"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/Hackn0/$AppID/data
        target: /data
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    x-casaos:
      ports:
        - container: "9000"
          description:
            en_us: Portainer Web UI Port
        - container: "9443"
          description:
            en_us: Portainer Web UI Port(https)
      volumes:
        - container: /data
          description:
            en_us: Portainer data directory
x-casaos:
  architectures:
    - amd64
  description:
    en_us: Portainer is a lightweight management UI which allows you to easily manage your Docker environments. It is designed to be easy to use and offers full control over your Docker hosts and containers.
  developer: Portainer
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Portainer/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Portainer/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Portainer/screenshot-2.png
  tagline:
    en_us: Lightweight Docker management UI
  thumbnail: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Portainer/thumbnail.png
  tips: null
  main: portainer
  title:
    en_us: Portainer
  index: /
  port_map: "9000"
  scheme: http
  author: portainer
  category: Hackn0
  store_app_id: portainer
